[pytest]
testpaths = test_case
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke
    regression: regression
addopts = -s -v --tb=short
junit_family=xunit1